### ISSUE TITLE
Not Working on Debian 12 / GNOME 43.9

### ISSUE THREAD

**Issue by billbeans** [Guldoman/mpv_inhibit_gnome#11]
This doesn't work for some reason on the latest Debian stable ("bookworm"). It worked for me on Ubuntu 22.04, which used GNOME 42.9, but not anymore. Screen blanks while watching video. I currently have it in `usr/share/mpv/scripts`, but even when having it in the .config folder the screen still blanks. What am I doing wrong, if anything?

**Comment by Guldoman** [comment]
Did you compile the plugin yourself, or is it the one from the release?

**Comment by billbeans** [comment]
> Did you compile the plugin yourself, or is it the one from the release?

I tried both in the past, but just to be sure, I recloned the repo, ran `make` and then `make install`. It seems to be working now, but I have been having lots of problems with screen blanking on GNOME lately; many times the screen will not blank at all, regardless of mpv being open or not, and I haven't identified the offending program(s) yet. 

I will re-open this issue if the problem comes back, because I absolutely did build and install the script in the past and it didn't work. The only difference is that I manually dragged the file into the config folder whereas this time I ran the `make install` command - I don't know how that would make a difference, I doubt it did, but it's worth mentioning

**Comment by Guldoman** [comment]
> many times the screen will not blank at all, regardless of mpv being open or not, and I haven't identified the offending program(s) yet.

When that happens, try running `gnome-session-inhibit -l`, it should tell you what's keeping it awake.
