### ISSUE TITLE
strcmp with nullptr

### ISSUE THREAD

**Issue by Deminder** [Guldoman/mpv_inhibit_gnome#2]
Hi @Guldoman,
I like the album art check. But I do get the motivation why you used bitfields ([does not seem necessary](https://stackoverflow.com/questions/1044654/bitfield-manipulation-in-c)).
However, maybe we should avoid passing `NULL` to `strcmp` here
https://github.com/Guldoman/mpv_inhibit_gnome/blob/a8b4d2c9be24baa7438e65778de512191406bb11/src/main.c#L45
https://github.com/Guldoman/mpv_inhibit_gnome/blob/a8b4d2c9be24baa7438e65778de512191406bb11/src/main.c#L149

See here:
https://stackoverflow.com/questions/21865041/in-c-what-exactly-happens-when-you-pass-a-null-pointer-to-strcmp

Additional confusion:
Why do we even need  `{NULL                            , MPV_FORMAT_NONE  }`?
Do we really need to check `value = data > 0` why not leave it at `value = data != 0`?
```
bool value = *(int64_t *)prop->data > 0;
```

**Comment by Guldoman** [comment]
> However, maybe we should avoid passing `NULL` to `strcmp` here

`strcmp` won't receive `NULL` from us because the `for` exits when it finds a `NULL` name:

https://github.com/Guldoman/mpv_inhibit_gnome/blob/a8b4d2c9be24baa7438e65778de512191406bb11/src/main.c#L147

> Additional confusion: Why do we even need `{NULL , MPV_FORMAT_NONE }`?

I used it to find the end of the array without having to keep track of its length.

> Do we really need to check `value = data > 0` why not leave it at `value = data != 0`?
> 
> ```
> bool value = *(int64_t *)prop->data > 0;
> ```

I don't know if `mpv` can send us a negative track, but I doubt it would be a valid one, so `> 0` covers that case.

**Comment by Deminder** [comment]
Ah okay, but wouldn't the union struct with
```c
typedef struct __attribute__((packed)) {
	bool pause;
	bool idle_active;
	bool stop_screensaver;
	bool window_minimized;
	bool mute;
	bool albumart;
	bool vid;
	bool aid;
} PropsFlags;
```
and `for(unsigned i = 0; i < sizeof(PropsFlags); i++)` be less confusing?

But since there is no bug I would be fine with closing this issue :shrug:

**Comment by Guldoman** [comment]
To be honest I find it more confusing, mostly because it needs the packed attribute to even work.
Also consider that `bool` is only guaranteed to be enough to contain true/false, but it can be bigger than 1 byte, which would make `sizeof` not work as you'd expect it to.

**Comment by Deminder** [comment]
All right :+1:
