### ISSUE TITLE
screen blanking since last flatpak dependincy update 

### ISSUE THREAD

**Issue by pflanzenandi** [Guldoman/mpv_inhibit_gnome#4]
The update removed the gnome.SessionManager override entry. But applying the override again, didn't fix the screen go blank.
Besides that, nothing has changes in my setup.

Am using `flatpak override --user --talk-name=org.gnome.SessionManager io.mpv.Mpv`

**Comment by Guldoman** [comment]
This should be fixed by #5. Could you confirm?
Also it looks like this plugin will be included in the flatpak release of mpv by default in the near future (flathub/io.mpv.Mpv#94).

**Comment by Guldoman** [comment]
Closing for now. Feel free to reopen if the issue is still present.

**Comment by Guldoman** [comment]
The plugin has been integrated into the Flatpak release, so you should remove the version you manually installed to avoid problems (`~/.var/app/io.mpv.Mpv/config/mpv/scripts/mpv_inhibit_gnome.so`).

**Comment by pflanzenandi** [comment]
I already did. Thanks for your support!
