### ISSUE TITLE
How about expanding it to cover other problems on Wayland Gnome?

### ISSUE THREAD

**Issue by HubKing** [Guldoman/mpv_inhibit_gnome#8]
I installed this using AUR and it has been working well. But sadly, sleeping was not the only problem I am having with MPV on Wayland Gnome. Since this plug-in already deals with Wayland Gnome, I wonder if you could add more fixes for other problems on Wayland Gnome, to make this plugin more like a one-stop "Wayland Gnome fix". If that does not fit the purpose of this plug-in, then maybe as separate plug-ins.

For example, "stay on top (shift +T)" does not work. I have to press alt+space and click "Always on Top" each time, and it has been a pain in the lower back. 

Also, it does not work to drag-and-drop a video file on a Samba network share from Gnome Files (nautilus) to MPV. If I know it correctly, Gnome maps network Samba file (e.g., `smb://server/file.mkv`) into a local virtual file (e.g.,  `/run/user/1000/gvfs/smb-share:server=server,share=file.mkv`) using GVFS, but Gnome Files passes the raw Samba address when drag-and-dropping and MPV developers seem to have no intention to support GVFS. If a plug-in could convert that Samba address into its locally mapped GVFS path, and tell MPV to play that local file path, MPV will be able to play it.

**Comment by Guldoman** [comment]
Thank you for your suggestion.
At the moment I'm not too interested in solving those problems, but I would create a plugin for each of these issues, as some of those could be useful outside of GNOME.

**Comment by HubKing** [comment]
Thanks for your consideration. 

But for some reason, D&D an SMB file to MPV somehow started working since I posted this. I don't know why. I think there was some large software update that included a lot of packages, so it could be the reason, but I am not sure.

**Comment by Guldoman** [comment]
For me D&D from an sftp mount works in nautilus but not in nemo. Didn't test nautilus before tho.
